#!/usr/bin/env python3
import os
import sys
import io
import csv

directory = sys.argv[1]
newfile = sys.argv[2]

content = []
for index, filename in enumerate(os.listdir(directory)):
    if filename.endswith(".csv"):
        with open(os.path.join(directory, filename)) as f:
            temp_content = [line.rstrip('\n') for line in f]
        if (index > 0): temp_content.pop(0)
        content.extend(temp_content)
        with open(os.path.join(newfile), 'w') as f:
            for item in content:
                f.write("%s\n" % item)
